# Generated by Django 3.0.1 on 2020-01-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='ke_pre',
            new_name='ke_pri',
        ),
    ]
