# Generated by Django 3.0.1 on 2020-01-04 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sense',
            name='reading_num',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='reading_num',
        ),
    ]
