# Generated by Django 3.0.1 on 2020-01-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20200104_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='g_gend',
            field=models.TextField(default='', verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='g_type',
            field=models.TextField(default='', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
