# Generated by Django 3.0.1 on 2020-01-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20200105_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='re_nokanji',
            field=models.BooleanField(verbose_name='No Kanji'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='re_restr',
            field=models.TextField(verbose_name='Reading Restrictions'),
        ),
    ]
