# Generated by Django 3.0.1 on 2020-01-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20200104_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='re_nokanji',
            field=models.TextField(default='', verbose_name='No Kanji'),
            preserve_default=False,
        ),
    ]
