# Generated by Django 3.0.2 on 2020-01-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='entry_id',
            new_name='example_id',
        ),
    ]
