# Generated by Django 3.0.2 on 2020-01-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='simple',
            field=models.TextField(default='', verbose_name='Simplified'),
        ),
    ]
